This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./plantillatfg.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file plantillatfg.acn....done (114 entries accepted, 0 rejected).
Sorting entries....done (874 comparisons).
Generating output file plantillatfg.acr....done (121 lines written, 0 warnings).
Output written in plantillatfg.acr.
Transcript written in plantillatfg.alg.
